# This workflow runs integration tests using
# the unicore-testing-all Docker container

name: Run all tests vs UFTP docker container

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  integration-test:

    runs-on: ubuntu-latest

    services:
      unicore:
        image: ghcr.io/unicore-eu/uftp-testing-all:3.2.0
        ports:
          - 9000:9000
          - 64434:64434
          - 50000-50010:50000-50010

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install .
        pip install -r requirements-dev.txt
    - name: Run tests
      run: |
        pytest

